<?php

namespace Database\Seeders;

use Carbon\Carbon;
use App\Models\ExploreLanguage;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // count 142

        $languages_list = [
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Afrikaans", "code" => "af", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Albanian", "code" => "sq", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Amharic", "code" => "am", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Arabic", "code" => "ar", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Aragonese", "code" => "an", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Armenian", "code" => "hy", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Asturian", "code" => "ast", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Azerbaijani", "code" => "az", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Basque", "code" => "eu", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Belarusian", "code" => "be", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Bengali", "code" => "bn", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Bosnian", "code" => "bs", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Breton", "code" => "br", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Bulgarian", "code" => "bg", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Catalan", "code" => "ca", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Central Kurdish", "code" => "ckb", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Chinese", "code" => "zh", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Chinese (Hong Kong)", "code" => "zh-H,K", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Chinese (Simplified)", "code" => "zh-C,N", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Chinese (Traditional)", "code" => "zh-T,W", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Corsican", "code" => "co", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Croatian", "code" => "hr", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Czech", "code" => "cs", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Danish", "code" => "da", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Dutch", "code" => "nl", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "English", "code" => "en", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "English (Australia)", "code" => "en-A,U", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "English (Canada)", "code" => "en-C,A", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "English (India)", "code" => "en-I,N", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "English (New Zealand)", "code" => "en-N,Z", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "English (South Africa)", "code" => "en-Z,A", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "English (United Kingdom)", "code" => "en-G,B", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "English (United States)", "code" => "en-U,S", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Esperanto", "code" => "eo", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Estonian", "code" => "et", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Faroese", "code" => "fo", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Filipino", "code" => "fil", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Finnish", "code" => "fi", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "French", "code" => "fr", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "French (Canada)", "code" => "fr-C,A", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "French (France)", "code" => "fr-F,R", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "French (Switzerland)", "code" => "fr-C,H", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Galician", "code" => "gl", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Georgian", "code" => "ka", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "German", "code" => "de", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "German (Austria)", "code" => "de-A,T", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "German (Germany)", "code" => "de-D,E", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "German (Liechtenstein)", "code" => "de-L,I", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "German (Switzerland)", "code" => "de-C,H", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Greek", "code" => "el", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Guarani", "code" => "gn", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Gujarati", "code" => "gu", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Hausa", "code" => "ha", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Hawaiian Hawaiʻi", "code" => "haw", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Hebrew", "code" => "he", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Hindi", "code" => "hi", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Hungarian", "code" => "hu", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Icelandic", "code" => "is", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Indonesian", "code" => "id", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Interlingua", "code" => "ia", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Irish", "code" => "ga", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Italian", "code" => "it", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Italian (Italy)", "code" => "it-I,T", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Italian (Switzerland)", "code" => "it-C,H", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Japanese", "code" => "ja", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Kannada", "code" => "kn", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Kazakh", "code" => "kk", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Khmer", "code" => "km", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Korean", "code" => "ko", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Kurdish", "code" => "ku", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Kyrgyz", "code" => "ky", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Lao", "code" => "lo", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Latin", "code" => "la", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Latvian", "code" => "lv", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Lingala", "code" => "ln", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Lithuanian", "code" => "lt", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Macedonian", "code" => "mk", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Malay", "code" => "ms", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Malayalam", "code" => "ml", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Maltese", "code" => "mt", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Marathi", "code" => "mr", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Mongolian", "code" => "mn", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Nepali", "code" => "ne", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Norwegian", "code" => "no", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Norwegian Bokmål", "code" => "nb", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Norwegian Nynorsk", "code" => "nn", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Occitan", "code" => "oc", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Oriya", "code" => "or", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Oromo", "code" => "om", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Pashto", "code" => "ps", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Persian", "code" => "fa", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Polish", "code" => "pl", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Portuguese", "code" => "pt", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Portuguese (Brazil)", "code" => "pt-B,R", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Portuguese (Portugal)", "code" => "pt-P,T", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Punjabi", "code" => "pa", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Quechua", "code" => "qu", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Romanian", "code" => "ro", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Romanian (Moldova)", "code" => "mo", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Romansh", "code" => "rm", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Russian", "code" => "ru", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Scottish Gaelic", "code" => "gd", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Serbian", "code" => "sr", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Serbo", "code" => "sh", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Shona", "code" => "sn", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Sindhi", "code" => "sd", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Sinhala", "code" => "si", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Slovak", "code" => "sk", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Slovenian", "code" => "sl", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Somali", "code" => "so", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Southern Sotho", "code" => "st", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Spanish", "code" => "es", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Spanish (Argentina)", "code" => "es-A,R", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Spanish (Latin America)", "code" => "es-4,19", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Spanish (Mexico)", "code" => "es-M,X", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Spanish (Spain)", "code" => "es-E,S", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Spanish (United States)", "code" => "es-U,S", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Sundanese", "code" => "su", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Swahili", "code" => "sw", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Swedish", "code" => "sv", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Tajik", "code" => "tg", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Tamil", "code" => "ta", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Tatar", "code" => "tt", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Telugu", "code" => "te", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Thai", "code" => "th", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Tigrinya", "code" => "ti", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Tongan", "code" => "to", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Turkish", "code" => "tr", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Turkmen", "code" => "tk", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Twi", "code" => "tw", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Ukrainian", "code" => "uk", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Urdu", "code" => "ur", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Uyghur", "code" => "ug", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Uzbek", "code" => "uz", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Vietnamese", "code" => "vi", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Walloon", "code" => "wa", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Welsh", "code" => "cy", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Western Frisian", "code" => "fy", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Xhosa", "code" => "xh", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Yiddish", "code" => "yi", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Yoruba", "code" => "yo", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => \Ramsey\Uuid\Uuid::uuid4()->toString(), "name" => "Zulu", "code" => "zu", 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()]
        ];

        ExploreLanguage::insert($languages_list);
    }
}
